# Generated by Django 5.0.6 on 2024-12-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/')),
            ],
        ),
        migrations.CreateModel(
            name='Excluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exclude', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Included',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='activities/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('map', models.TextField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('period', models.PositiveIntegerField(help_text='Period in minutes')),
                ('days_off', models.CharField(blank=True, help_text='Days off (comma-separated)', max_length=255, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('start_time', models.TimeField(help_text='Start time of the activity')),
                ('end_time', models.TimeField(help_text='End time of the activity')),
                ('audio_languages', models.TextField(blank=True, null=True)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('group_size', models.CharField(blank=True, max_length=50, null=True)),
                ('participant_age_range', models.CharField(blank=True, max_length=50, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='activities', to='categories.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('subcategories', models.ManyToManyField(blank=True, related_name='activities', to='categories.subcategory')),
                ('sublocations', models.ManyToManyField(blank=True, related_name='activities', to='location.sublocation')),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
    ]
