# Generated by Django 5.0.6 on 2024-12-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplier'),
        ),
        migrations.AddField(
            model_name='activityoffer',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AddField(
            model_name='excluded',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AddField(
            model_name='faq',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AddField(
            model_name='included',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AddField(
            model_name='period',
            name='activity_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='activities.activityoffer'),
        ),
    ]
