# Generated by Django 5.0.6 on 2024-12-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_family_activity_local_favorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activity',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
