# Generated by Django 5.0.6 on 2024-12-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplier'),
        ),
        migrations.AddField(
            model_name='itinerarystep',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_step_set', to='packages.package'),
        ),
        migrations.AddField(
            model_name='included',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
        migrations.AddField(
            model_name='faq',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
        migrations.AddField(
            model_name='excluded',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
        migrations.AddField(
            model_name='packageoffer',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='packages.package'),
        ),
        migrations.AddField(
            model_name='packageday',
            name='package_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packageoffer'),
        ),
    ]
