# Generated by Django 5.0.6 on 2024-12-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_family_tour_local_favorites_tour_seasonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tour',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
