# Generated by Django 5.0.6 on 2024-12-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_initial'),
        ('booking', '0001_initial'),
        ('packages', '0001_initial'),
        ('tours', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitybooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='activitybooking',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.period'),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='package_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packageoffer'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='tourday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourday'),
        ),
    ]
