# Generated by Django 5.0.6 on 2025-01-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='governorate',
            field=models.CharField(choices=[('Beirut', 'Beirut'), ('Mount Lebanon', 'Mount Lebanon'), ('North Lebanon', 'North Lebanon'), ('Akkar', 'Akkar'), ('Baalbek-Hermel', 'Baalbek-Hermel'), ('Bekaa', 'Bekaa'), ('South Lebanon', 'South Lebanon'), ('Nabatieh', 'Nabatieh'), ('Keserwan', 'Keserwan')], default='Beirut', max_length=50),
        ),
    ]
